with open('mx_sony.m3u', 'w') as f:
    f.write('#EXTM3U url-tvg="http://botallen.live/epg.xml.gz"\n')

    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Sony_HD.png" group-title="Entertainment",SONY HD')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/HgaB-u6rSpGx3mo4Xu3sLw/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Sony_SAB.png" group-title="Entertainment",SAB HD')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/UI4QFJ_uRk6aLxIcADqa_A/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Sony_Pal.png" group-title="Entertainment",SONY PAL')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/rPzF28qORbKZkhci_04fdQ/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Sony_Max_HD.png" group-title="Movie",SONY MAX HD')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/HgaB-u6rSpGx3mo4Xu3sLw/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/SET_MAX.png" group-title="Movie",SONY MAX')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/oJ-TGgVFSgSMBUoTkauvFQ/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Sony_Wah.png" group-title="Movie",SONY WAH')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/H_ZvXWqHRGKpHcdDE5RcDA/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Sony_MAX2.png" group-title="Movie",SONY MAX2')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/4Jcu195QTpCNBXGnpw2I6g/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Sony_Pix_HD.png" group-title="Movie",SONY PIX HD')
    f.write('\nhttps://pubads.g.doubleclick.net/ssai/event/8FR5Q-WfRWCkbMq_GxZ77w/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-id="144" tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Six_HD.png" group-title="Sports",SONY SIX HD')
    f.write('\nhttps://pubads.g.doubleclick.net:443/ssai/event/DD7fA-HgSUaLyZp9AjRYxQ/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-id="144" tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Ten_HD.png" group-title="Sports",SONY TEN 1 HD')
    f.write('\nhttps://pubads.g.doubleclick.net:443/ssai/event/yeYP86THQ4yl7US8Zx5eug/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-id="144" tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Ten2_HD.png" group-title="Sports",SONY TEN 2 HD')
    f.write('\nhttps://pubads.g.doubleclick.net:443/ssai/event/Syu8F41-R1y_JmQ7x0oNxQ/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-id="144" tvg-logo="http://jiotv.catchup.cdn.jio.com/dare_images/images/Ten3_HD.png" group-title="Sports",SONY TEN 3 HD')
    f.write('\nhttps://pubads.g.doubleclick.net:443/ssai/event/nmQFuHURTYGQBNdUG-2Qdw/master.m3u8')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="STAR Sports 1 HD" tvg-logo="" group-title="Sports",STAR Sports 1 HD')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241506')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="STAR Sports 2 HD" tvg-logo="" group-title="Sports",STAR Sports 2 HD')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241505')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="STAR Sports Select 1 HD" tvg-logo="" group-title="Sports",STAR Sports Select 1 HD')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241504')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="STAR Sports Select 2 HD" tvg-logo="" group-title="Sports",STAR Sports Select 2 HD')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241503')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="DD Sports" tvg-logo="" group-title="Sports",DD Sports')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241499')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="Eurosport HD" tvg-logo="" group-title="Sports",Eurosport HD')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241498')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="Eurosport" tvg-logo="" group-title="Sports",Eurosport')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241497')
    f.write('\n#EXTINF:-1 tvg-id="" tvg-name="1sports" tvg-logo="" group-title="Sports",1sports')
    f.write('\nhttp://echootv.tv:2086/sipantaroyan_FMUqUy/SdhIHYZ5Fz/241496')
    f.write('\n#EXTINF:-1 tvg-logo="" group-title="Entertainment",Colors HD')
    f.write('\nhttp://103.217.221.64/snehjiotv/snehjioo.php?c=Colors_HD&q=800&e=.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="" group-title="Entertainment",Rishtey')
    f.write('\nhttp://103.217.221.64/snehjiotv/snehjioo.php?c=Rishtey&q=800&e=.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="" group-title="Movie",Rishtey_Cineplex')
    f.write('\nhttp://103.217.221.64/snehjiotv/snehjioo.php?c=Rishtey_Cineplex&q=800&e=.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="" group-title="Movie",B4U_Movies')
    f.write('\nhttp://103.217.221.64/snehjiotv/snehjioo.php?c=B4U_Movies&q=800&e=.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="" group-title="Movie",Enterr_10')
    f.write('\nhttp://103.217.221.64/snehjiotv/snehjioo.php?c=Enterr_10&q=800&e=.m3u8')
    f.write('\n#EXTINF:-1 tvg-logo="" group-title="Music",Zing')
    f.write('\nhttp://103.217.221.64/snehjiotv/snehjioo.php?c=Zing&q=800&e=.m3u8')